UPDATE products SET product_name = 'A4 Spiral Notebook' WHERE product_id = 1;
UPDATE products SET product_name = 'Desk Organizer Tray' WHERE product_id = 2;
UPDATE products SET product_name = 'Birthday Greeting Card Set' WHERE product_id = 3;
UPDATE products SET product_name = 'Introduction to Algorithms' WHERE product_id = 4;
UPDATE products SET product_name = 'Blue Ballpoint Pen Pack' WHERE product_id = 5;
UPDATE products SET product_name = 'Decorative Photo Frame' WHERE product_id = 6;
UPDATE products SET product_name = 'Cable Storage Box' WHERE product_id = 7;
UPDATE products SET product_name = 'Data Structures Handbook' WHERE product_id = 8;
UPDATE products SET product_name = 'Mini Whiteboard' WHERE product_id = 9;
UPDATE products SET product_name = 'Sticky Notes Set' WHERE product_id = 10;
UPDATE products SET product_name = 'Python Programming Guide' WHERE product_id = 11;
UPDATE products SET product_name = 'Executive Diary 2026' WHERE product_id = 12;
UPDATE products SET product_name = 'English Grammar Essentials' WHERE product_id = 13;
UPDATE products SET product_name = 'Wireless Optical Mouse' WHERE product_id = 14;
UPDATE products SET product_name = 'Chocolate Gift Box' WHERE product_id = 15;
UPDATE products SET product_name = 'Transparent File Folder' WHERE product_id = 16;
UPDATE products SET product_name = 'Premium Marker Set' WHERE product_id = 17;
UPDATE products SET product_name = 'Couple Mug Gift Set' WHERE product_id = 18;
UPDATE products SET product_name = 'LED Desk Lamp Gift Edition' WHERE product_id = 19;
UPDATE products SET product_name = 'USB Keyboard' WHERE product_id = 20;
UPDATE products SET product_name = 'Multipurpose Storage Basket' WHERE product_id = 21;
UPDATE products SET product_name = 'Bluetooth Neckband Earphones' WHERE product_id = 22;
UPDATE products SET product_name = 'Hardcover Sketchbook' WHERE product_id = 23;
UPDATE products SET product_name = 'Portable Phone Charger' WHERE product_id = 24;
UPDATE products SET product_name = 'Machine Learning Basics' WHERE product_id = 25;
UPDATE products SET product_name = 'Resin Flower Showpiece' WHERE product_id = 26;
UPDATE products SET product_name = 'Smart Fitness Band' WHERE product_id = 27;
UPDATE products SET product_name = 'Gel Pen Color Pack' WHERE product_id = 28;
UPDATE products SET product_name = 'Laptop Sleeve 15 Inch' WHERE product_id = 29;
UPDATE products SET product_name = 'Acrylic Desk Name Plate' WHERE product_id = 30;
UPDATE products SET product_name = 'Wireless Presenter Remote' WHERE product_id = 31;
UPDATE products SET product_name = 'Pocket Dictionary' WHERE product_id = 32;
UPDATE products SET product_name = 'Festival Gift Hamper' WHERE product_id = 33;
UPDATE products SET product_name = 'Noise Cancelling Headphones' WHERE product_id = 34;
UPDATE products SET product_name = 'Office Stapler Set' WHERE product_id = 35;
UPDATE products SET product_name = 'Clipboard Writing Board' WHERE product_id = 36;
UPDATE products SET product_name = 'USB Flash Drive 64GB' WHERE product_id = 37;
UPDATE products SET product_name = 'Metal Utility Rack' WHERE product_id = 38;
UPDATE products SET product_name = 'Portable Bluetooth Speaker' WHERE product_id = 39;
UPDATE products SET product_name = 'Exam Writing Pad' WHERE product_id = 40;
UPDATE products SET product_name = 'Mechanical Keyboard' WHERE product_id = 41;
UPDATE products SET product_name = 'Personalized Key Ring' WHERE product_id = 42;
UPDATE products SET product_name = 'Crystal Pen Stand Gift' WHERE product_id = 43;
UPDATE products SET product_name = 'Highlighter Pen Set' WHERE product_id = 44;
UPDATE products SET product_name = 'Wooden Table Decor' WHERE product_id = 45;
UPDATE products SET product_name = 'Travel Pouch Organizer' WHERE product_id = 46;
UPDATE products SET product_name = 'Smart Watch Series Lite' WHERE product_id = 47;
UPDATE products SET product_name = 'Magazine Holder Rack' WHERE product_id = 48;
UPDATE products SET product_name = 'Correction Tape Pack' WHERE product_id = 49;
UPDATE products SET product_name = 'Foldable Laptop Table' WHERE product_id = 50;
UPDATE products SET product_name = 'Luxury Gift Basket' WHERE product_id = 51;
UPDATE products SET product_name = 'Document Carry Bag' WHERE product_id = 52;
UPDATE products SET product_name = 'Wooden Desk Clock' WHERE product_id = 53;
UPDATE products SET product_name = 'Academic Writing Guide' WHERE product_id = 54;
UPDATE products SET product_name = 'Anniversary Gift Box' WHERE product_id = 55;
UPDATE products SET product_name = 'Planner Notebook Pro' WHERE product_id = 56;
UPDATE products SET product_name = 'Scented Candle Gift Set' WHERE product_id = 57;
UPDATE products SET product_name = 'Desk Calendar Stand' WHERE product_id = 58;
UPDATE products SET product_name = 'Black Ink Roller Pen' WHERE product_id = 59;
UPDATE products SET product_name = 'Custom Photo Mug' WHERE product_id = 60;
UPDATE products SET product_name = 'Heart Cushion Gift' WHERE product_id = 61;
UPDATE products SET product_name = 'Mini Teddy Bear' WHERE product_id = 62;
UPDATE products SET product_name = 'Wireless Earbuds' WHERE product_id = 63;
UPDATE products SET product_name = 'Travel Memory Scrapbook' WHERE product_id = 64;
UPDATE products SET product_name = 'Glass Trophy Gift' WHERE product_id = 65;
UPDATE products SET product_name = 'Office Scissors Set' WHERE product_id = 66;
UPDATE products SET product_name = 'Portable SSD 1TB' WHERE product_id = 67;
UPDATE products SET product_name = 'Gaming Mouse Pad XL' WHERE product_id = 68;
UPDATE products SET product_name = '1080p Webcam' WHERE product_id = 69;
UPDATE products SET product_name = 'Discrete Mathematics Textbook' WHERE product_id = 70;
UPDATE products SET product_name = 'Operating Systems Concepts' WHERE product_id = 71;
UPDATE products SET product_name = 'Desktop File Sorter' WHERE product_id = 72;
UPDATE products SET product_name = 'Wireless Router AC1200' WHERE product_id = 73;
UPDATE products SET product_name = 'Rose Bouquet Gift Wrap' WHERE product_id = 74;
UPDATE products SET product_name = 'Portable Storage Ottoman' WHERE product_id = 75;
UPDATE products SET product_name = 'Love Message Bottle Gift' WHERE product_id = 76;
UPDATE products SET product_name = 'Fountain Pen Signature Edition' WHERE product_id = 77;
UPDATE products SET product_name = 'Office Binder Clips Jar' WHERE product_id = 78;
UPDATE products SET product_name = 'Handmade Gift Basket Deluxe' WHERE product_id = 79;
UPDATE products SET product_name = 'Subject Divider Notebook' WHERE product_id = 80;
UPDATE products SET product_name = 'Drawer Utility Bin' WHERE product_id = 81;
UPDATE products SET product_name = 'Premium Fountain Pen' WHERE product_id = 82;
UPDATE products SET product_name = 'Gift Wrapping Ribbon Box' WHERE product_id = 83;
UPDATE products SET product_name = 'Whiteboard Marker Combo' WHERE product_id = 84;
UPDATE products SET product_name = 'School Stationery Kit' WHERE product_id = 85;
UPDATE products SET product_name = 'Android TV Stick' WHERE product_id = 86;
UPDATE products SET product_name = 'Portable Monitor 15.6 Inch' WHERE product_id = 87;
UPDATE products SET product_name = 'Graphic Drawing Tablet' WHERE product_id = 88;
UPDATE products SET product_name = 'Desk Pen Holder' WHERE product_id = 89;
UPDATE products SET product_name = 'Laptop Cooling Pad' WHERE product_id = 90;
UPDATE products SET product_name = 'World History Illustrated' WHERE product_id = 91;
UPDATE products SET product_name = 'Modern Poetry Collection' WHERE product_id = 92;
UPDATE products SET product_name = 'Handcrafted Gift Card Pack' WHERE product_id = 93;
UPDATE products SET product_name = 'Office Writing Essentials Box' WHERE product_id = 94;
UPDATE products SET product_name = 'Premium Office Stationery Set' WHERE product_id = 95;
UPDATE products SET product_name = 'Plastic Drawer Divider' WHERE product_id = 96;
UPDATE products SET product_name = 'Linear Algebra for Beginners' WHERE product_id = 97;
UPDATE products SET product_name = 'Surprise Gift Explosion Box' WHERE product_id = 98;
UPDATE products SET product_name = 'Under Desk Storage Tray' WHERE product_id = 99;
UPDATE products SET product_name = 'Personalized Chocolate Hamper' WHERE product_id = 100;


UPDATE products SET product_name = 'Wireless Keyboard Combo' WHERE product_id = 101;
UPDATE products SET product_name = 'Desktop Utility Box' WHERE product_id = 102;
UPDATE products SET product_name = 'Gift Paper Bag Set' WHERE product_id = 103;
UPDATE products SET product_name = 'Database Systems Concepts' WHERE product_id = 104;
UPDATE products SET product_name = 'Office Index Tabs' WHERE product_id = 105;
UPDATE products SET product_name = 'Plastic Storage Crate' WHERE product_id = 106;
UPDATE products SET product_name = 'Computer Networks Textbook' WHERE product_id = 107;
UPDATE products SET product_name = 'Algorithms Reference Manual' WHERE product_id = 108;
UPDATE products SET product_name = 'Digital Logic Fundamentals' WHERE product_id = 109;
UPDATE products SET product_name = 'Software Engineering Guide' WHERE product_id = 110;
UPDATE products SET product_name = 'Permanent Marker Pack' WHERE product_id = 111;
UPDATE products SET product_name = 'Compiler Design Basics' WHERE product_id = 112;
UPDATE products SET product_name = 'Mini Gift Box Set' WHERE product_id = 113;
UPDATE products SET product_name = 'Office Desk Pad' WHERE product_id = 114;
UPDATE products SET product_name = 'Probability and Statistics' WHERE product_id = 115;
UPDATE products SET product_name = 'Business Mathematics Book' WHERE product_id = 116;
UPDATE products SET product_name = 'Color Sticky Flags' WHERE product_id = 117;
UPDATE products SET product_name = 'USB Charging Hub' WHERE product_id = 118;
UPDATE products SET product_name = 'Writing Essentials Bundle' WHERE product_id = 119;
UPDATE products SET product_name = 'Student Stationery Box' WHERE product_id = 120;
UPDATE products SET product_name = 'Short Story Collection' WHERE product_id = 121;
UPDATE products SET product_name = 'Mesh Desk Basket' WHERE product_id = 122;
UPDATE products SET product_name = 'Wooden Utility Stand' WHERE product_id = 123;
UPDATE products SET product_name = 'Portable Projector Mini' WHERE product_id = 124;
UPDATE products SET product_name = 'Decor Storage Container' WHERE product_id = 125;
UPDATE products SET product_name = 'Bluetooth Speaker Mini' WHERE product_id = 126;
UPDATE products SET product_name = 'English Literature Notes' WHERE product_id = 127;
UPDATE products SET product_name = 'Embedded Systems Handbook' WHERE product_id = 128;
UPDATE products SET product_name = 'Custom Gift Voucher Box' WHERE product_id = 129;
UPDATE products SET product_name = 'Exam Preparation File' WHERE product_id = 130;
UPDATE products SET product_name = 'Color Pencil Set' WHERE product_id = 131;
UPDATE products SET product_name = 'Acrylic Trophy Gift' WHERE product_id = 132;
UPDATE products SET product_name = 'USB Desk Fan' WHERE product_id = 133;
UPDATE products SET product_name = 'Microprocessor Architecture' WHERE product_id = 134;
UPDATE products SET product_name = 'Office Tape Dispenser' WHERE product_id = 135;
UPDATE products SET product_name = 'Phone Tripod Stand' WHERE product_id = 136;
UPDATE products SET product_name = 'Advanced Programming Book' WHERE product_id = 137;
UPDATE products SET product_name = 'Fabric Storage Pouch' WHERE product_id = 138;
UPDATE products SET product_name = 'Festival Surprise Box' WHERE product_id = 139;
UPDATE products SET product_name = 'Premium Desk Folder' WHERE product_id = 140;
UPDATE products SET product_name = 'Foldable Utility Basket' WHERE product_id = 141;
UPDATE products SET product_name = 'Rose Gift Card Pack' WHERE product_id = 142;
UPDATE products SET product_name = 'Laptop Stand Adjustable' WHERE product_id = 143;
UPDATE products SET product_name = 'Portable Bluetooth Keyboard' WHERE product_id = 144;
UPDATE products SET product_name = 'Personalized Gift Envelope' WHERE product_id = 145;
UPDATE products SET product_name = 'USB Microphone' WHERE product_id = 146;
UPDATE products SET product_name = 'Office Pins Box' WHERE product_id = 147;
UPDATE products SET product_name = 'Mini Love Scrapbook' WHERE product_id = 148;
UPDATE products SET product_name = 'Decorative Candle Gift' WHERE product_id = 149;
UPDATE products SET product_name = 'Photo Album Gift Set' WHERE product_id = 150;
UPDATE products SET product_name = 'Portable Barcode Scanner' WHERE product_id = 151;
UPDATE products SET product_name = 'Fundamentals of Physics' WHERE product_id = 152;
UPDATE products SET product_name = 'Ring Binder Notebook' WHERE product_id = 153;
UPDATE products SET product_name = 'Discrete Structures Book' WHERE product_id = 154;
UPDATE products SET product_name = 'Multipurpose Desk Tray' WHERE product_id = 155;
UPDATE products SET product_name = 'WiFi Range Extender' WHERE product_id = 156;
UPDATE products SET product_name = 'Planner Journal Set' WHERE product_id = 157;
UPDATE products SET product_name = 'Handmade Flower Basket' WHERE product_id = 158;
UPDATE products SET product_name = 'Label Sticker Pack' WHERE product_id = 159;
UPDATE products SET product_name = 'Office Paper Cutter' WHERE product_id = 160;
UPDATE products SET product_name = 'English Vocabulary Builder' WHERE product_id = 161;
UPDATE products SET product_name = 'Desk Cable Clip Set' WHERE product_id = 162;
UPDATE products SET product_name = 'Novel Gift Edition' WHERE product_id = 163;
UPDATE products SET product_name = 'Drawer Organizer Box' WHERE product_id = 164;
UPDATE products SET product_name = 'Wardrobe Storage Box' WHERE product_id = 165;
UPDATE products SET product_name = 'Academic Planner Book' WHERE product_id = 166;
UPDATE products SET product_name = 'Luxury Pen Gift Set' WHERE product_id = 167;
UPDATE products SET product_name = 'Paper Fastener Box' WHERE product_id = 168;
UPDATE products SET product_name = 'Mini Surprise Hamper' WHERE product_id = 169;
UPDATE products SET product_name = 'Premium Gift Basket Large' WHERE product_id = 170;
UPDATE products SET product_name = 'Office Register Book' WHERE product_id = 171;
UPDATE products SET product_name = 'Utility Shelf Organizer' WHERE product_id = 172;
UPDATE products SET product_name = 'Correction Pen Pack' WHERE product_id = 173;
UPDATE products SET product_name = 'Storage Drawer Tower' WHERE product_id = 174;
UPDATE products SET product_name = 'Calligraphy Marker Set' WHERE product_id = 175;
UPDATE products SET product_name = 'USB Docking Station' WHERE product_id = 176;
UPDATE products SET product_name = 'Premium Gift Card Hamper' WHERE product_id = 177;
UPDATE products SET product_name = 'Artificial Intelligence Basics' WHERE product_id = 178;
UPDATE products SET product_name = 'Smart Home Plug' WHERE product_id = 179;
UPDATE products SET product_name = 'Personalized Cushion Gift' WHERE product_id = 180;
UPDATE products SET product_name = 'Chocolate Surprise Card' WHERE product_id = 181;
UPDATE products SET product_name = 'Fundamentals of Accounting' WHERE product_id = 182;
UPDATE products SET product_name = 'Desk File Cabinet Mini' WHERE product_id = 183;
UPDATE products SET product_name = 'Premium Writing Notebook' WHERE product_id = 184;
UPDATE products SET product_name = 'Decorative Glass Jar Gift' WHERE product_id = 185;
UPDATE products SET product_name = 'Portable Hard Drive 2TB' WHERE product_id = 186;
UPDATE products SET product_name = 'Paper Clip Holder' WHERE product_id = 187;
UPDATE products SET product_name = 'Object Oriented Programming' WHERE product_id = 188;
UPDATE products SET product_name = 'Signals and Systems Book' WHERE product_id = 189;
UPDATE products SET product_name = 'Office Utility Stand' WHERE product_id = 190;
UPDATE products SET product_name = 'Smartphone Gimbal Stabilizer' WHERE product_id = 191;
UPDATE products SET product_name = 'Celebration Gift Basket' WHERE product_id = 192;
UPDATE products SET product_name = 'Couple Memory Box' WHERE product_id = 193;
UPDATE products SET product_name = 'Children Story Book' WHERE product_id = 194;
UPDATE products SET product_name = 'Customized Photo Keychain' WHERE product_id = 195;
UPDATE products SET product_name = 'Bluetooth Headset' WHERE product_id = 196;
UPDATE products SET product_name = 'Classical Literature Reader' WHERE product_id = 197;
UPDATE products SET product_name = 'Professional Ethics Book' WHERE product_id = 198;
UPDATE products SET product_name = 'Research Methods Book' WHERE product_id = 199;
UPDATE products SET product_name = 'Document Storage Box' WHERE product_id = 200;
UPDATE products SET product_name = 'USB Type C Adapter' WHERE product_id = 201;
UPDATE products SET product_name = 'Rotating Desk Organizer' WHERE product_id = 202;
UPDATE products SET product_name = 'Greeting Card Premium Set' WHERE product_id = 203;
UPDATE products SET product_name = 'Anniversary Photo Frame' WHERE product_id = 204;
UPDATE products SET product_name = 'Portable Utility Rack' WHERE product_id = 205;
UPDATE products SET product_name = 'Wireless Gaming Mouse' WHERE product_id = 206;
UPDATE products SET product_name = 'Smart LED Bulb' WHERE product_id = 207;
UPDATE products SET product_name = 'Study Notes Folder' WHERE product_id = 208;
UPDATE products SET product_name = 'Executive Office Kit' WHERE product_id = 209;
UPDATE products SET product_name = 'Bluetooth Presenter Clicker' WHERE product_id = 210;
UPDATE products SET product_name = 'Fine Tip Pen Set' WHERE product_id = 211;
UPDATE products SET product_name = 'World Civilization Book' WHERE product_id = 212;
UPDATE products SET product_name = 'Desk Stationery Holder' WHERE product_id = 213;
UPDATE products SET product_name = 'Premium Executive Diary' WHERE product_id = 214;
UPDATE products SET product_name = 'Mini Desktop Drawer' WHERE product_id = 215;
UPDATE products SET product_name = 'Streaming Webcam Pro' WHERE product_id = 216;
UPDATE products SET product_name = 'Luxury Chocolate Gift Box' WHERE product_id = 217;
UPDATE products SET product_name = 'Creative Writing Handbook' WHERE product_id = 218;
UPDATE products SET product_name = 'Portable Desk Clock' WHERE product_id = 219;
UPDATE products SET product_name = 'Fundamentals of Economics' WHERE product_id = 220;
UPDATE products SET product_name = 'Wireless Numeric Keypad' WHERE product_id = 221;
UPDATE products SET product_name = 'Romantic Gift Basket' WHERE product_id = 222;
UPDATE products SET product_name = 'Tablet Drawing Pen' WHERE product_id = 223;
UPDATE products SET product_name = 'Canvas Storage Bin' WHERE product_id = 224;
UPDATE products SET product_name = 'Student Assignment Notebook' WHERE product_id = 225;
UPDATE products SET product_name = 'Whiteboard Duster Set' WHERE product_id = 226;
UPDATE products SET product_name = 'Business Communication Book' WHERE product_id = 227;
UPDATE products SET product_name = 'Plastic Drawer Box' WHERE product_id = 228;
UPDATE products SET product_name = 'Book Shelf Organizer' WHERE product_id = 229;
UPDATE products SET product_name = 'USB Reading Lamp' WHERE product_id = 230;
UPDATE products SET product_name = 'Adhesive Notes Combo' WHERE product_id = 231;
UPDATE products SET product_name = 'Smart Desk Clock' WHERE product_id = 232;
UPDATE products SET product_name = 'Storage Basket Woven' WHERE product_id = 233;
UPDATE products SET product_name = 'Portable Voice Recorder' WHERE product_id = 234;
UPDATE products SET product_name = 'Office Desk Caddy' WHERE product_id = 235;
UPDATE products SET product_name = 'Magazine Storage Rack' WHERE product_id = 236;
UPDATE products SET product_name = 'Wireless Mini Printer' WHERE product_id = 237;
UPDATE products SET product_name = 'Exam Solution Book' WHERE product_id = 238;
UPDATE products SET product_name = 'Professional Journal Book' WHERE product_id = 239;
UPDATE products SET product_name = 'Data Communication Concepts' WHERE product_id = 240;
UPDATE products SET product_name = 'Marker Pen Office Set' WHERE product_id = 241;
UPDATE products SET product_name = 'Smart WiFi Camera' WHERE product_id = 242;
UPDATE products SET product_name = 'Portable SSD Case' WHERE product_id = 243;
UPDATE products SET product_name = 'Desk Accessory Kit' WHERE product_id = 244;
UPDATE products SET product_name = 'Pocket Memo Pad' WHERE product_id = 245;
UPDATE products SET product_name = 'Java Programming Complete' WHERE product_id = 246;
UPDATE products SET product_name = 'Luxury Chocolate Bouquet' WHERE product_id = 247;
UPDATE products SET product_name = 'Mini Utility Container' WHERE product_id = 248;
UPDATE products SET product_name = 'Engineering Mathematics' WHERE product_id = 249;
UPDATE products SET product_name = 'Operating System Workbook' WHERE product_id = 250;
UPDATE products SET product_name = 'Wireless Desk Charger' WHERE product_id = 251;
UPDATE products SET product_name = 'Student Writing Pad' WHERE product_id = 252;
UPDATE products SET product_name = 'Smart Desk Lamp' WHERE product_id = 253;
UPDATE products SET product_name = 'Elegant Gift Hamper' WHERE product_id = 254;
UPDATE products SET product_name = 'History of English Literature' WHERE product_id = 255;
UPDATE products SET product_name = 'Rose Box Gift Set' WHERE product_id = 256;
UPDATE products SET product_name = 'Customized Candle Hamper' WHERE product_id = 257;
UPDATE products SET product_name = 'Numerical Methods Book' WHERE product_id = 258;
UPDATE products SET product_name = 'Linear Algebra Workbook' WHERE product_id = 259;
UPDATE products SET product_name = 'Premium Journal Notebook' WHERE product_id = 260;
UPDATE products SET product_name = 'Desktop File Tray' WHERE product_id = 261;
UPDATE products SET product_name = 'Modern Drama Collection' WHERE product_id = 262;
UPDATE products SET product_name = 'Photo Scrapbook Gift' WHERE product_id = 263;
UPDATE products SET product_name = 'Student Lab Notebook' WHERE product_id = 264;
UPDATE products SET product_name = 'Festival Sweets Hamper' WHERE product_id = 265;
UPDATE products SET product_name = 'Multipurpose Organizer Case' WHERE product_id = 266;
UPDATE products SET product_name = 'Planner Sticky Note Set' WHERE product_id = 267;
UPDATE products SET product_name = 'Handmade Gift Bouquet' WHERE product_id = 268;
UPDATE products SET product_name = 'Portable Bluetooth Soundbar' WHERE product_id = 269;
UPDATE products SET product_name = 'Theory of Computation' WHERE product_id = 270;
UPDATE products SET product_name = 'Memory Box Deluxe' WHERE product_id = 271;
UPDATE products SET product_name = 'Wireless Mechanical Keyboard' WHERE product_id = 272;
UPDATE products SET product_name = 'Office Writing Kit Pro' WHERE product_id = 273;
UPDATE products SET product_name = 'Phone Stand Foldable' WHERE product_id = 274;
UPDATE products SET product_name = 'Color Highlighter Set' WHERE product_id = 275;
UPDATE products SET product_name = 'Staple Pin Refill Box' WHERE product_id = 276;
UPDATE products SET product_name = 'Romantic Surprise Hamper' WHERE product_id = 277;
UPDATE products SET product_name = 'Photo Memory Album' WHERE product_id = 278;
UPDATE products SET product_name = 'Decorative Storage Jar' WHERE product_id = 279;
UPDATE products SET product_name = 'Wireless Presenter Pro' WHERE product_id = 280;
UPDATE products SET product_name = 'Office Utility Cabinet' WHERE product_id = 281;
UPDATE products SET product_name = 'Mini Desk Clock Cute' WHERE product_id = 282;
UPDATE products SET product_name = 'Introduction to Sociology' WHERE product_id = 283;
UPDATE products SET product_name = 'Document Tray Stackable' WHERE product_id = 284;
UPDATE products SET product_name = 'Business Law Essentials' WHERE product_id = 285;
UPDATE products SET product_name = 'Desktop Office Essentials Kit' WHERE product_id = 286;
UPDATE products SET product_name = 'Binder Clip Office Pack' WHERE product_id = 287;
UPDATE products SET product_name = 'Network Security Basics' WHERE product_id = 288;
UPDATE products SET product_name = 'Storage Bin Modular' WHERE product_id = 289;
UPDATE products SET product_name = 'Wooden Gift Card Box' WHERE product_id = 290;
UPDATE products SET product_name = 'Mini Celebration Hamper' WHERE product_id = 291;
UPDATE products SET product_name = 'Wireless Conference Speaker' WHERE product_id = 292;
UPDATE products SET product_name = 'Portable Study Lamp' WHERE product_id = 293;
UPDATE products SET product_name = 'Advanced Office Stationery Set' WHERE product_id = 294;
UPDATE products SET product_name = 'Heart Shape Gift Box' WHERE product_id = 295;
UPDATE products SET product_name = 'Electrical Circuits Book' WHERE product_id = 296;
UPDATE products SET product_name = 'Introduction to Philosophy' WHERE product_id = 297;
UPDATE products SET product_name = 'Gift Ribbon Pack' WHERE product_id = 298;
UPDATE products SET product_name = 'Smart Plug Dual Port' WHERE product_id = 299;
UPDATE products SET product_name = 'USB Desk Vacuum Cleaner' WHERE product_id = 300;


UPDATE products SET product_name = 'Portable Label Printer' WHERE product_id = 301;
UPDATE products SET product_name = 'Desk Storage Cabinet' WHERE product_id = 302;
UPDATE products SET product_name = 'Advanced Database Systems' WHERE product_id = 303;
UPDATE products SET product_name = 'Computer Graphics Book' WHERE product_id = 304;
UPDATE products SET product_name = 'Luxury Greeting Hamper' WHERE product_id = 305;
UPDATE products SET product_name = 'Office Push Pin Set' WHERE product_id = 306;
UPDATE products SET product_name = 'Chocolate Card Surprise' WHERE product_id = 307;
UPDATE products SET product_name = 'Digital Electronics Book' WHERE product_id = 308;
UPDATE products SET product_name = 'Wooden Desk Drawer' WHERE product_id = 309;
UPDATE products SET product_name = 'Portable USB Fan' WHERE product_id = 310;
UPDATE products SET product_name = 'Executive Pen Stand' WHERE product_id = 311;
UPDATE products SET product_name = 'Academic Research Handbook' WHERE product_id = 312;
UPDATE products SET product_name = 'Formal Languages and Automata' WHERE product_id = 313;
UPDATE products SET product_name = 'Desktop Utility Shelf' WHERE product_id = 314;
UPDATE products SET product_name = 'Premium Art Journal' WHERE product_id = 315;
UPDATE products SET product_name = 'Plastic Office Drawer' WHERE product_id = 316;
UPDATE products SET product_name = 'Fundamentals of Marketing' WHERE product_id = 317;
UPDATE products SET product_name = 'Heart Box Chocolate Gift' WHERE product_id = 318;
UPDATE products SET product_name = 'Anniversary Memory Scrapbook' WHERE product_id = 319;
UPDATE products SET product_name = 'Handmade Surprise Card' WHERE product_id = 320;
UPDATE products SET product_name = 'USB Graphics Tablet' WHERE product_id = 321;
UPDATE products SET product_name = 'Office Journal Folder' WHERE product_id = 322;
UPDATE products SET product_name = 'Mini Bluetooth Tracker' WHERE product_id = 323;
UPDATE products SET product_name = 'Gift Message Envelope' WHERE product_id = 324;
UPDATE products SET product_name = 'Student Project Notebook' WHERE product_id = 325;
UPDATE products SET product_name = 'Foldable Cloth Organizer' WHERE product_id = 326;
UPDATE products SET product_name = 'Luxury Teddy Gift Box' WHERE product_id = 327;
UPDATE products SET product_name = 'Laptop USB Hub' WHERE product_id = 328;
UPDATE products SET product_name = 'Portable Reading Light' WHERE product_id = 329;
UPDATE products SET product_name = 'Office Signature Pen Set' WHERE product_id = 330;
UPDATE products SET product_name = 'Mini Power Bank' WHERE product_id = 331;
UPDATE products SET product_name = 'Storage Box Compact' WHERE product_id = 332;
UPDATE products SET product_name = 'Desk Shelf Rack' WHERE product_id = 333;
UPDATE products SET product_name = 'Decorative Basket Organizer' WHERE product_id = 334;
UPDATE products SET product_name = 'Wireless Presenter Pointer' WHERE product_id = 335;
UPDATE products SET product_name = 'Premium Fountain Pen Set' WHERE product_id = 336;
UPDATE products SET product_name = 'Portable Photo Printer' WHERE product_id = 337;
UPDATE products SET product_name = 'Sticky Memo Cube' WHERE product_id = 338;
UPDATE products SET product_name = 'USB Desk Lamp Pro' WHERE product_id = 339;
UPDATE products SET product_name = 'Smart Wireless Charger' WHERE product_id = 340;
UPDATE products SET product_name = 'Mesh Paper Tray' WHERE product_id = 341;
UPDATE products SET product_name = 'English Composition Book' WHERE product_id = 342;
UPDATE products SET product_name = 'Multi Layer Storage Rack' WHERE product_id = 343;
UPDATE products SET product_name = 'Office Document Wallet' WHERE product_id = 344;
UPDATE products SET product_name = 'Fundamentals of Finance' WHERE product_id = 345;
UPDATE products SET product_name = 'Classic Novel Gift Edition' WHERE product_id = 346;
UPDATE products SET product_name = 'Premium Desk Stapler' WHERE product_id = 347;
UPDATE products SET product_name = 'Wooden Book Stand' WHERE product_id = 348;
UPDATE products SET product_name = 'Executive Writing Set' WHERE product_id = 349;
UPDATE products SET product_name = 'True Wireless Earbuds' WHERE product_id = 350;
UPDATE products SET product_name = 'Decor Gift Jar Set' WHERE product_id = 351;
UPDATE products SET product_name = 'Poetry Anthology Collection' WHERE product_id = 352;
UPDATE products SET product_name = 'Wireless Soundbar Mini' WHERE product_id = 353;
UPDATE products SET product_name = 'Photo Frame Gift Combo' WHERE product_id = 354;
UPDATE products SET product_name = 'Correction Fluid Pen' WHERE product_id = 355;
UPDATE products SET product_name = 'Desktop Accessory Rack' WHERE product_id = 356;
UPDATE products SET product_name = 'Modern Fiction Reader' WHERE product_id = 357;
UPDATE products SET product_name = 'Storage Drawer Organizer' WHERE product_id = 358;
UPDATE products SET product_name = 'Utility Basket Round' WHERE product_id = 359;
UPDATE products SET product_name = 'Campus Stationery Box' WHERE product_id = 360;
UPDATE products SET product_name = 'Human Resource Management' WHERE product_id = 361;
UPDATE products SET product_name = 'Plastic Storage Tub' WHERE product_id = 362;
UPDATE products SET product_name = 'Discrete Mathematics Workbook' WHERE product_id = 363;
UPDATE products SET product_name = 'Office Cable Organizer' WHERE product_id = 364;
UPDATE products SET product_name = 'Bluetooth Stereo Headphones' WHERE product_id = 365;
UPDATE products SET product_name = 'Custom Trophy Gift' WHERE product_id = 366;
UPDATE products SET product_name = 'Portable Storage Bin' WHERE product_id = 367;
UPDATE products SET product_name = 'Mini Utility Basket' WHERE product_id = 368;
UPDATE products SET product_name = 'Gift Wrap Sticker Set' WHERE product_id = 369;
UPDATE products SET product_name = 'Presentation Marker Pack' WHERE product_id = 370;
UPDATE products SET product_name = 'Practice Exercise Notebook' WHERE product_id = 371;
UPDATE products SET product_name = 'Business English Book' WHERE product_id = 372;
UPDATE products SET product_name = 'USB Rechargeable Torch' WHERE product_id = 373;
UPDATE products SET product_name = 'Contemporary World Literature' WHERE product_id = 374;
UPDATE products SET product_name = 'Sociology Theory Book' WHERE product_id = 375;
UPDATE products SET product_name = 'Premium Student Stationery Pack' WHERE product_id = 376;
UPDATE products SET product_name = 'Love Note Gift Set' WHERE product_id = 377;
UPDATE products SET product_name = 'Desk Utility Bin' WHERE product_id = 378;
UPDATE products SET product_name = 'Storage Folder Deluxe' WHERE product_id = 379;
UPDATE products SET product_name = 'Wireless Keyboard Slim' WHERE product_id = 380;
UPDATE products SET product_name = 'Permanent Marker Office Pack' WHERE product_id = 381;
UPDATE products SET product_name = 'Environmental Science Book' WHERE product_id = 382;
UPDATE products SET product_name = 'Portable Ring Light' WHERE product_id = 383;
UPDATE products SET product_name = 'Gift Hamper Medium' WHERE product_id = 384;
UPDATE products SET product_name = 'Cyber Security Fundamentals' WHERE product_id = 385;
UPDATE products SET product_name = 'Mini USB Humidifier' WHERE product_id = 386;
UPDATE products SET product_name = 'Rose Surprise Basket' WHERE product_id = 387;
UPDATE products SET product_name = 'Desktop Drawer Mini' WHERE product_id = 388;
UPDATE products SET product_name = 'Utility Storage Rack' WHERE product_id = 389;
UPDATE products SET product_name = 'Engineering Mechanics Book' WHERE product_id = 390;
UPDATE products SET product_name = 'USB Speaker Compact' WHERE product_id = 391;
UPDATE products SET product_name = 'Fabric Storage Basket' WHERE product_id = 392;
UPDATE products SET product_name = 'Office Note Register' WHERE product_id = 393;
UPDATE products SET product_name = 'Portable Media Player' WHERE product_id = 394;
UPDATE products SET product_name = 'Smartphone Stabilizer' WHERE product_id = 395;
UPDATE products SET product_name = 'Business Statistics Textbook' WHERE product_id = 396;
UPDATE products SET product_name = 'Desk Memo Pad Set' WHERE product_id = 397;
UPDATE products SET product_name = 'Luxury Gift Envelope' WHERE product_id = 398;
UPDATE products SET product_name = 'Exam Preparation Journal' WHERE product_id = 399;
UPDATE products SET product_name = 'Theory of Machines' WHERE product_id = 400;
UPDATE products SET product_name = 'Anniversary Candle Basket' WHERE product_id = 401;
UPDATE products SET product_name = 'Campus Note Organizer' WHERE product_id = 402;
UPDATE products SET product_name = 'USB Mini Vacuum' WHERE product_id = 403;
UPDATE products SET product_name = 'Hardcover Planner Diary' WHERE product_id = 404;
UPDATE products SET product_name = 'Large Utility Storage Box' WHERE product_id = 405;
UPDATE products SET product_name = 'Festival Gift Card' WHERE product_id = 406;
UPDATE products SET product_name = 'Portable Voice Amplifier' WHERE product_id = 407;
UPDATE products SET product_name = 'Sticky Flags Office Set' WHERE product_id = 408;
UPDATE products SET product_name = 'Desk Supply Pouch' WHERE product_id = 409;
UPDATE products SET product_name = 'Custom Memory Frame' WHERE product_id = 410;
UPDATE products SET product_name = 'Decorative Chocolate Basket' WHERE product_id = 411;
UPDATE products SET product_name = 'Mini Teddy Surprise' WHERE product_id = 412;
UPDATE products SET product_name = 'Love Photo Album' WHERE product_id = 413;
UPDATE products SET product_name = 'Introduction to Linguistics' WHERE product_id = 414;
UPDATE products SET product_name = 'Acrylic Gift Trophy' WHERE product_id = 415;
UPDATE products SET product_name = 'Technical Writing Book' WHERE product_id = 416;
UPDATE products SET product_name = 'Premium Stationery Pouch' WHERE product_id = 417;
UPDATE products SET product_name = 'Executive File Organizer' WHERE product_id = 418;
UPDATE products SET product_name = 'Portable SSD Drive' WHERE product_id = 419;
UPDATE products SET product_name = 'Mini Love Card Box' WHERE product_id = 420;
UPDATE products SET product_name = 'Student Writing Tool Kit' WHERE product_id = 421;
UPDATE products SET product_name = 'Wireless Charging Dock' WHERE product_id = 422;
UPDATE products SET product_name = 'Chocolate Rose Combo' WHERE product_id = 423;
UPDATE products SET product_name = 'USB Desk Clock' WHERE product_id = 424;
UPDATE products SET product_name = 'Classroom Stationery Set' WHERE product_id = 425;
UPDATE products SET product_name = 'Luxury Pen Holder' WHERE product_id = 426;
UPDATE products SET product_name = 'Portable Smart Plug' WHERE product_id = 427;
UPDATE products SET product_name = 'Bluetooth Rechargeable Mouse' WHERE product_id = 428;
UPDATE products SET product_name = 'Premium Mug Gift Set' WHERE product_id = 429;
UPDATE products SET product_name = 'Wooden Utility Drawer' WHERE product_id = 430;
UPDATE products SET product_name = 'Mini USB Speaker' WHERE product_id = 431;
UPDATE products SET product_name = 'Portable Webcam Cover Pack' WHERE product_id = 432;
UPDATE products SET product_name = 'Storage File Box' WHERE product_id = 433;
UPDATE products SET product_name = 'Business Ethics Book' WHERE product_id = 434;
UPDATE products SET product_name = 'Desk Highlighter Set' WHERE product_id = 435;
UPDATE products SET product_name = 'Romantic Chocolate Box' WHERE product_id = 436;
UPDATE products SET product_name = 'Customized Photo Stand' WHERE product_id = 437;
UPDATE products SET product_name = 'Drawer Organizer Compact' WHERE product_id = 438;
UPDATE products SET product_name = 'USB Multimedia Keyboard' WHERE product_id = 439;
UPDATE products SET product_name = 'World History Reader' WHERE product_id = 440;
UPDATE products SET product_name = 'Multi Purpose Storage Case' WHERE product_id = 441;
UPDATE products SET product_name = 'Office Planner Book' WHERE product_id = 442;
UPDATE products SET product_name = 'Computer Organization Book' WHERE product_id = 443;
UPDATE products SET product_name = 'Gift Hamper Premium Deluxe' WHERE product_id = 444;
UPDATE products SET product_name = 'Portable SSD Enclosure' WHERE product_id = 445;
UPDATE products SET product_name = 'Luxury Memory Basket' WHERE product_id = 446;
UPDATE products SET product_name = 'Teddy Chocolate Combo' WHERE product_id = 447;
UPDATE products SET product_name = 'Desktop Cable Basket' WHERE product_id = 448;
UPDATE products SET product_name = 'Crystal Lamp Gift' WHERE product_id = 449;
UPDATE products SET product_name = 'Greeting Card Love Edition' WHERE product_id = 450;
UPDATE products SET product_name = 'Mathematical Methods Book' WHERE product_id = 451;
UPDATE products SET product_name = 'Storage Utility Crate' WHERE product_id = 452;
UPDATE products SET product_name = 'Research Methodology Textbook' WHERE product_id = 453;
UPDATE products SET product_name = 'Academic Reference Book' WHERE product_id = 454;
UPDATE products SET product_name = 'Premium Sticky Notes Pack' WHERE product_id = 455;
UPDATE products SET product_name = 'USB Conference Microphone' WHERE product_id = 456;
UPDATE products SET product_name = 'Operating Systems Workbook' WHERE product_id = 457;
UPDATE products SET product_name = 'Decorative Gift Tray' WHERE product_id = 458;
UPDATE products SET product_name = 'Mini Handmade Card' WHERE product_id = 459;
UPDATE products SET product_name = 'Storage Pouch Canvas' WHERE product_id = 460;
UPDATE products SET product_name = 'Laptop Riser Stand' WHERE product_id = 461;
UPDATE products SET product_name = 'Office Utility Drawer Box' WHERE product_id = 462;
UPDATE products SET product_name = 'Contemporary Poetry Book' WHERE product_id = 463;
UPDATE products SET product_name = 'Mesh Pen Cup' WHERE product_id = 464;
UPDATE products SET product_name = 'Luxury Mug Basket' WHERE product_id = 465;
UPDATE products SET product_name = 'Student Stationery Folder' WHERE product_id = 466;
UPDATE products SET product_name = 'Office Desk Pad Premium' WHERE product_id = 467;
UPDATE products SET product_name = 'Plastic Storage Folder' WHERE product_id = 468;
UPDATE products SET product_name = 'Academic Pocket Dictionary' WHERE product_id = 469;
UPDATE products SET product_name = 'Couple Photo Hamper' WHERE product_id = 470;
UPDATE products SET product_name = 'Premium Filing Clips Set' WHERE product_id = 471;
UPDATE products SET product_name = 'Executive Note Diary' WHERE product_id = 472;
UPDATE products SET product_name = 'Mini Teddy Gift Pack' WHERE product_id = 473;
UPDATE products SET product_name = 'Chocolate Note Hamper' WHERE product_id = 474;
UPDATE products SET product_name = 'Utility Box Large' WHERE product_id = 475;
UPDATE products SET product_name = 'Bluetooth Neck Speaker' WHERE product_id = 476;
UPDATE products SET product_name = 'Student Paper Clip Box' WHERE product_id = 477;
UPDATE products SET product_name = 'Storage Divider Tray' WHERE product_id = 478;
UPDATE products SET product_name = 'Short Stories Reader' WHERE product_id = 479;
UPDATE products SET product_name = 'Portable Travel Adapter' WHERE product_id = 480;
UPDATE products SET product_name = 'Desk Stationery Basket' WHERE product_id = 481;
UPDATE products SET product_name = 'Mini Decorative Shelf' WHERE product_id = 482;
UPDATE products SET product_name = 'Executive Marker Set' WHERE product_id = 483;
UPDATE products SET product_name = 'Business Communication Skills' WHERE product_id = 484;
UPDATE products SET product_name = 'Gift Candle Jar' WHERE product_id = 485;
UPDATE products SET product_name = 'Children Literature Book' WHERE product_id = 486;
UPDATE products SET product_name = 'Modern Poetry Reader' WHERE product_id = 487;
UPDATE products SET product_name = 'Portable Desk Fan Mini' WHERE product_id = 488;
UPDATE products SET product_name = 'Premium Desk Organizer Pro' WHERE product_id = 489;
UPDATE products SET product_name = 'Wireless Streaming Device' WHERE product_id = 490;
UPDATE products SET product_name = 'Photo Gift Explosion Box' WHERE product_id = 491;
UPDATE products SET product_name = 'Engineering Drawing Book' WHERE product_id = 492;
UPDATE products SET product_name = 'Compiler Construction Guide' WHERE product_id = 493;
UPDATE products SET product_name = 'Fundamentals of Management' WHERE product_id = 494;
UPDATE products SET product_name = 'Office Register Ledger' WHERE product_id = 495;
UPDATE products SET product_name = 'Document Carry Folder' WHERE product_id = 496;
UPDATE products SET product_name = 'Mini Gel Pen Pack' WHERE product_id = 497;
UPDATE products SET product_name = 'Drawer Storage Rack' WHERE product_id = 498;
UPDATE products SET product_name = 'Luxury Chocolate Bouquet' WHERE product_id = 499;
UPDATE products SET product_name = 'Portable SSD Hub' WHERE product_id = 500;
UPDATE products SET product_name = 'Storage Tray Mini' WHERE product_id = 501;
UPDATE products SET product_name = 'Executive Clip Folder' WHERE product_id = 502;
UPDATE products SET product_name = 'Bluetooth Keyboard Case' WHERE product_id = 503;
UPDATE products SET product_name = 'Premium Writing Board' WHERE product_id = 504;
UPDATE products SET product_name = 'USB Smart Desk Lamp' WHERE product_id = 505;
UPDATE products SET product_name = 'Office Correction Pen' WHERE product_id = 506;
UPDATE products SET product_name = 'Business Analytics Book' WHERE product_id = 507;
UPDATE products SET product_name = 'Portable Audio Receiver' WHERE product_id = 508;
UPDATE products SET product_name = 'Desktop Storage Bin' WHERE product_id = 509;
UPDATE products SET product_name = 'Mini Handmade Gift Box' WHERE product_id = 510;
UPDATE products SET product_name = 'Premium Planner Diary' WHERE product_id = 511;
UPDATE products SET product_name = 'Student Sticky Flag Set' WHERE product_id = 512;
UPDATE products SET product_name = 'Introduction to Psychology' WHERE product_id = 513;
UPDATE products SET product_name = 'Office Utility Basket' WHERE product_id = 514;
UPDATE products SET product_name = 'Crystal Heart Gift' WHERE product_id = 515;
UPDATE products SET product_name = 'Desktop Paper Holder' WHERE product_id = 516;
UPDATE products SET product_name = 'Data Science Handbook' WHERE product_id = 517;
UPDATE products SET product_name = 'Wireless Audio Adapter' WHERE product_id = 518;
UPDATE products SET product_name = 'Executive Signature Journal' WHERE product_id = 519;
UPDATE products SET product_name = 'Business Law Workbook' WHERE product_id = 520;
UPDATE products SET product_name = 'Drawer Tray Organizer' WHERE product_id = 521;
UPDATE products SET product_name = 'Portable Study Speaker' WHERE product_id = 522;
UPDATE products SET product_name = 'Storage Box Utility Pro' WHERE product_id = 523;
UPDATE products SET product_name = 'Gift Card Box Mini' WHERE product_id = 524;
UPDATE products SET product_name = 'Premium Note Register' WHERE product_id = 525;
UPDATE products SET product_name = 'Wireless Charging Stand' WHERE product_id = 526;
UPDATE products SET product_name = 'Plastic Stationery Rack' WHERE product_id = 527;
UPDATE products SET product_name = 'Mini Ribbon Gift Set' WHERE product_id = 528;
UPDATE products SET product_name = 'Business Writing Book' WHERE product_id = 529;
UPDATE products SET product_name = 'Bluetooth Party Speaker' WHERE product_id = 530;
UPDATE products SET product_name = 'Desk Clip Board Pro' WHERE product_id = 531;
UPDATE products SET product_name = 'Storage Drawer Fabric' WHERE product_id = 532;
UPDATE products SET product_name = 'Engineering Physics Book' WHERE product_id = 533;
UPDATE products SET product_name = 'Academic Workbook Set' WHERE product_id = 534;
UPDATE products SET product_name = 'Portable Smart Light' WHERE product_id = 535;
UPDATE products SET product_name = 'Student Note Binder' WHERE product_id = 536;
UPDATE products SET product_name = 'Premium Whiteboard Kit' WHERE product_id = 537;
UPDATE products SET product_name = 'Utility Storage Crate Mini' WHERE product_id = 538;
UPDATE products SET product_name = 'Desk Pen Set Deluxe' WHERE product_id = 539;
UPDATE products SET product_name = 'Customized Surprise Basket' WHERE product_id = 540;
UPDATE products SET product_name = 'Office Marker Holder' WHERE product_id = 541;
UPDATE products SET product_name = 'Wireless HDMI Dongle' WHERE product_id = 542;
UPDATE products SET product_name = 'Executive Paper Folder' WHERE product_id = 543;
UPDATE products SET product_name = 'Storage Caddy Rack' WHERE product_id = 544;
UPDATE products SET product_name = 'Love Message Bottle' WHERE product_id = 545;
UPDATE products SET product_name = 'Portable Ring Fill Light' WHERE product_id = 546;
UPDATE products SET product_name = 'Desk Calendar Pro' WHERE product_id = 547;
UPDATE products SET product_name = 'Luxury Teddy Basket' WHERE product_id = 548;
UPDATE products SET product_name = 'Decorative Wood Tray' WHERE product_id = 549;
UPDATE products SET product_name = 'Introduction to Journalism' WHERE product_id = 550;
UPDATE products SET product_name = 'Campus Writing Essentials' WHERE product_id = 551;
UPDATE products SET product_name = 'Photo Memory Gift Pack' WHERE product_id = 552;
UPDATE products SET product_name = 'Computer Architecture Book' WHERE product_id = 553;
UPDATE products SET product_name = 'Plastic Drawer Caddy' WHERE product_id = 554;
UPDATE products SET product_name = 'English Pronunciation Guide' WHERE product_id = 555;
UPDATE products SET product_name = 'Premium Office Journal' WHERE product_id = 556;
UPDATE products SET product_name = 'Storage Container Office' WHERE product_id = 557;
UPDATE products SET product_name = 'Luxury Gift Rose Box' WHERE product_id = 558;
UPDATE products SET product_name = 'Custom Candle Gift Set' WHERE product_id = 559;
UPDATE products SET product_name = 'Anniversary Chocolate Combo' WHERE product_id = 560;
UPDATE products SET product_name = 'Portable Media Remote' WHERE product_id = 561;
UPDATE products SET product_name = 'Wireless Charging Pad' WHERE product_id = 562;
UPDATE products SET product_name = 'Storage File Tray' WHERE product_id = 563;
UPDATE products SET product_name = 'Office Shelf Organizer' WHERE product_id = 564;
UPDATE products SET product_name = 'Fundamentals of Education' WHERE product_id = 565;
UPDATE products SET product_name = 'Sticky Label Office Pack' WHERE product_id = 566;
UPDATE products SET product_name = 'Photo Frame Surprise Gift' WHERE product_id = 567;
UPDATE products SET product_name = 'Premium Sharpener Set' WHERE product_id = 568;
UPDATE products SET product_name = 'USB Presentation Clicker' WHERE product_id = 569;
UPDATE products SET product_name = 'Custom Mug and Card Set' WHERE product_id = 570;
UPDATE products SET product_name = 'Executive Desk Clock Pro' WHERE product_id = 571;
UPDATE products SET product_name = 'Portable Smart Socket' WHERE product_id = 572;
UPDATE products SET product_name = 'Storage Wallet Folder' WHERE product_id = 573;
UPDATE products SET product_name = 'Desk Journal Organizer' WHERE product_id = 574;
UPDATE products SET product_name = 'Celebration Chocolate Hamper' WHERE product_id = 575;
UPDATE products SET product_name = 'Premium Marker Box' WHERE product_id = 576;
UPDATE products SET product_name = 'USB Video Capture Device' WHERE product_id = 577;
UPDATE products SET product_name = 'Student Record Book' WHERE product_id = 578;
UPDATE products SET product_name = 'Professional Notebook Set' WHERE product_id = 579;
UPDATE products SET product_name = 'Portable File Cabinet' WHERE product_id = 580;
UPDATE products SET product_name = 'Memory Scrapbook Deluxe' WHERE product_id = 581;
UPDATE products SET product_name = 'Love Chocolate Basket' WHERE product_id = 582;
UPDATE products SET product_name = 'Desk Utility Planner' WHERE product_id = 583;
UPDATE products SET product_name = 'Portable USB Pointer' WHERE product_id = 584;
UPDATE products SET product_name = 'Bluetooth Desktop Speaker' WHERE product_id = 585;
UPDATE products SET product_name = 'Practical Grammar Book' WHERE product_id = 586;
UPDATE products SET product_name = 'Student Whiteboard Marker' WHERE product_id = 587;
UPDATE products SET product_name = 'Romantic Gift Explosion Box' WHERE product_id = 588;
UPDATE products SET product_name = 'Luxury Candle Hamper' WHERE product_id = 589;
UPDATE products SET product_name = 'History Reference Book' WHERE product_id = 590;
UPDATE products SET product_name = 'Document Box Archive' WHERE product_id = 591;
UPDATE products SET product_name = 'Desk Storage Shelf Pro' WHERE product_id = 592;
UPDATE products SET product_name = 'Executive Correction Kit' WHERE product_id = 593;
UPDATE products SET product_name = 'Portable Bluetooth Receiver' WHERE product_id = 594;
UPDATE products SET product_name = 'Storage Basket Tall' WHERE product_id = 595;
UPDATE products SET product_name = 'Premium Study Sticky Notes' WHERE product_id = 596;
UPDATE products SET product_name = 'Storage Pocket Notebook' WHERE product_id = 597;
UPDATE products SET product_name = 'Modern Essay Collection' WHERE product_id = 598;
UPDATE products SET product_name = 'Dictionary Pocket Edition' WHERE product_id = 599;
UPDATE products SET product_name = 'Academic Writing Register' WHERE product_id = 600;
UPDATE products SET product_name = 'Research Notes Journal' WHERE product_id = 601;
UPDATE products SET product_name = 'Executive File Cabinet Mini' WHERE product_id = 602;
UPDATE products SET product_name = 'Gift Card Flower Box' WHERE product_id = 603;
UPDATE products SET product_name = 'Photo Frame Hamper' WHERE product_id = 604;
UPDATE products SET product_name = 'Wireless Smart Switch' WHERE product_id = 605;
UPDATE products SET product_name = 'Storage Box Small' WHERE product_id = 606;
UPDATE products SET product_name = 'Introduction to Anthropology' WHERE product_id = 607;
UPDATE products SET product_name = 'Custom Surprise Jar' WHERE product_id = 608;
UPDATE products SET product_name = 'Desk Organizer Deluxe' WHERE product_id = 609;
UPDATE products SET product_name = 'Computer Programming Basics' WHERE product_id = 610;
UPDATE products SET product_name = 'Fine Tip Marker Set' WHERE product_id = 611;
UPDATE products SET product_name = 'Portable Audio Converter' WHERE product_id = 612;
UPDATE products SET product_name = 'USB WiFi Adapter' WHERE product_id = 613;
UPDATE products SET product_name = 'Executive Pencil Box' WHERE product_id = 614;
UPDATE products SET product_name = 'Storage Document Case' WHERE product_id = 615;
UPDATE products SET product_name = 'Love Note Gift Basket' WHERE product_id = 616;
UPDATE products SET product_name = 'Premium Office Diary 2026' WHERE product_id = 617;
UPDATE products SET product_name = 'Campus Planner Notebook' WHERE product_id = 618;
UPDATE products SET product_name = 'Storage Utility Stand' WHERE product_id = 619;
UPDATE products SET product_name = 'Portable Screen Cleaner' WHERE product_id = 620;
UPDATE products SET product_name = 'Professional Marker Set' WHERE product_id = 621;
UPDATE products SET product_name = 'Crystal Rose Gift' WHERE product_id = 622;
UPDATE products SET product_name = 'Smart Presentation Device' WHERE product_id = 623;
UPDATE products SET product_name = 'Desk Label Sticker Box' WHERE product_id = 624;
UPDATE products SET product_name = 'Wireless Office Doorbell' WHERE product_id = 625;
UPDATE products SET product_name = 'Anniversary Photo Gift Box' WHERE product_id = 626;
UPDATE products SET product_name = 'Student Register File' WHERE product_id = 627;
UPDATE products SET product_name = 'Modern Drama Reader' WHERE product_id = 628;
UPDATE products SET product_name = 'Handmade Love Basket' WHERE product_id = 629;
UPDATE products SET product_name = 'Executive Binder Folder' WHERE product_id = 630;
UPDATE products SET product_name = 'Document Shelf Tray' WHERE product_id = 631;
UPDATE products SET product_name = 'Financial Accounting Book' WHERE product_id = 632;
UPDATE products SET product_name = 'Computer Networks Workbook' WHERE product_id = 633;
UPDATE products SET product_name = 'Office Writing Register' WHERE product_id = 634;
UPDATE products SET product_name = 'Advanced Economics Textbook' WHERE product_id = 635;
UPDATE products SET product_name = 'Introduction to Geography' WHERE product_id = 636;
UPDATE products SET product_name = 'Storage Bin File Box' WHERE product_id = 637;
UPDATE products SET product_name = 'Phonetics and Phonology' WHERE product_id = 638;
UPDATE products SET product_name = 'Portable File Organizer' WHERE product_id = 639;
UPDATE products SET product_name = 'Desk Utility Cup' WHERE product_id = 640;
UPDATE products SET product_name = 'Classic Novel Collection' WHERE product_id = 641;
UPDATE products SET product_name = 'Research Card Index Set' WHERE product_id = 642;
UPDATE products SET product_name = 'Luxury Surprise Gift Pack' WHERE product_id = 643;
UPDATE products SET product_name = 'Storage Drawer Slim' WHERE product_id = 644;
UPDATE products SET product_name = 'Executive Study Lamp' WHERE product_id = 645;
UPDATE products SET product_name = 'Desktop Utility Compartment' WHERE product_id = 646;
UPDATE products SET product_name = 'Bluetooth USB Receiver' WHERE product_id = 647;
UPDATE products SET product_name = 'Academic Reference Notes' WHERE product_id = 648;
UPDATE products SET product_name = 'Campus Writing Folder' WHERE product_id = 649;
UPDATE products SET product_name = 'Programming Lab Manual' WHERE product_id = 650;
UPDATE products SET product_name = 'Mini Chocolate Gift Set' WHERE product_id = 651;
UPDATE products SET product_name = 'Data Structures Workbook' WHERE product_id = 652;
UPDATE products SET product_name = 'Student Desk Planner' WHERE product_id = 653;
UPDATE products SET product_name = 'Premium Sticky Memo Set' WHERE product_id = 654;
UPDATE products SET product_name = 'USB Multiport Adapter' WHERE product_id = 655;
UPDATE products SET product_name = 'Wireless Media Keyboard' WHERE product_id = 656;
UPDATE products SET product_name = 'Luxury Chocolate Card Box' WHERE product_id = 657;
UPDATE products SET product_name = 'Executive Desk Notepad' WHERE product_id = 658;
UPDATE products SET product_name = 'Principles of Sociology' WHERE product_id = 659;
UPDATE products SET product_name = 'Storage Rack Compact' WHERE product_id = 660;
UPDATE products SET product_name = 'Portable Multimedia Hub' WHERE product_id = 661;
UPDATE products SET product_name = 'Desk Journal Wallet' WHERE product_id = 662;
UPDATE products SET product_name = 'Premium Marker Organizer' WHERE product_id = 663;
UPDATE products SET product_name = 'World Literature Reader' WHERE product_id = 664;
UPDATE products SET product_name = 'Principles of Management' WHERE product_id = 665;
UPDATE products SET product_name = 'History Workbook Edition' WHERE product_id = 666;
UPDATE products SET product_name = 'English Reading Companion' WHERE product_id = 667;
UPDATE products SET product_name = 'Portable Presentation Speaker' WHERE product_id = 668;
UPDATE products SET product_name = 'Storage Drawer Box Pro' WHERE product_id = 669;
UPDATE products SET product_name = 'Desk Office Essentials Set' WHERE product_id = 670;
UPDATE products SET product_name = 'USB Wireless Mouse' WHERE product_id = 671;
UPDATE products SET product_name = 'Executive Shelf Basket' WHERE product_id = 672;
UPDATE products SET product_name = 'Premium Fountain Pen Deluxe' WHERE product_id = 673;
UPDATE products SET product_name = 'Storage Memo Basket' WHERE product_id = 674;
UPDATE products SET product_name = 'Bluetooth Keyboard Pro' WHERE product_id = 675;
UPDATE products SET product_name = 'Utility Storage Folder' WHERE product_id = 676;
UPDATE products SET product_name = 'Portable Streaming Stick' WHERE product_id = 677;
UPDATE products SET product_name = 'Modern Fiction Classics' WHERE product_id = 678;
UPDATE products SET product_name = 'Executive Office Tray' WHERE product_id = 679;
UPDATE products SET product_name = 'Desk Adhesive Note Set' WHERE product_id = 680;
UPDATE products SET product_name = 'Luxury Gift Card Basket' WHERE product_id = 681;
UPDATE products SET product_name = 'Romantic Teddy Hamper' WHERE product_id = 682;
UPDATE products SET product_name = 'Children Story Classics' WHERE product_id = 683;
UPDATE products SET product_name = 'Principles of Accounting' WHERE product_id = 684;
UPDATE products SET product_name = 'Portable Smart Speaker' WHERE product_id = 685;
UPDATE products SET product_name = 'Custom Memory Gift Box' WHERE product_id = 686;
UPDATE products SET product_name = 'Wireless Presenter Elite' WHERE product_id = 687;
UPDATE products SET product_name = 'USB Ambient Lamp' WHERE product_id = 688;
UPDATE products SET product_name = 'Premium Celebration Basket' WHERE product_id = 689;
UPDATE products SET product_name = 'Business Correspondence Book' WHERE product_id = 690;
UPDATE products SET product_name = 'Storage Utility Shelf Mini' WHERE product_id = 691;
UPDATE products SET product_name = 'Desk Stationery Drawer' WHERE product_id = 692;
UPDATE products SET product_name = 'Wireless Audio Hub' WHERE product_id = 693;
UPDATE products SET product_name = 'Executive Storage Box' WHERE product_id = 694;
UPDATE products SET product_name = 'Advanced Programming Concepts' WHERE product_id = 695;
UPDATE products SET product_name = 'Premium Notebook Planner' WHERE product_id = 696;
UPDATE products SET product_name = 'Mini Surprise Mug Set' WHERE product_id = 697;
UPDATE products SET product_name = 'Customized Chocolate Hamper' WHERE product_id = 698;
UPDATE products SET product_name = 'Love Card Gift Pack' WHERE product_id = 699;
UPDATE products SET product_name = 'Portable Office Speaker' WHERE product_id = 700;
UPDATE products SET product_name = 'Executive Writing Folder' WHERE product_id = 701;
UPDATE products SET product_name = 'Desk Pen Basket' WHERE product_id = 702;
UPDATE products SET product_name = 'Advanced Statistics Book' WHERE product_id = 703;
UPDATE products SET product_name = 'Premium Desk Utility Kit' WHERE product_id = 704;
UPDATE products SET product_name = 'Student Marker Board Set' WHERE product_id = 705;
UPDATE products SET product_name = 'Office Writing Pad Deluxe' WHERE product_id = 706;
UPDATE products SET product_name = 'Modern Business English' WHERE product_id = 707;
UPDATE products SET product_name = 'Campus Study Organizer' WHERE product_id = 708;
UPDATE products SET product_name = 'Introduction to Communication' WHERE product_id = 709;
UPDATE products SET product_name = 'Academic Library Companion' WHERE product_id = 710;
UPDATE products SET product_name = 'Classic Poetry Selection' WHERE product_id = 711;
UPDATE products SET product_name = 'Storage Drawer Station' WHERE product_id = 712;
UPDATE products SET product_name = 'Portable Desk Humidifier' WHERE product_id = 713;
UPDATE products SET product_name = 'USB Rechargeable Fan' WHERE product_id = 714;
UPDATE products SET product_name = 'Premium Writing Marker Set' WHERE product_id = 715;
UPDATE products SET product_name = 'Student Highlighter Bundle' WHERE product_id = 716;
UPDATE products SET product_name = 'Desk Journal Box' WHERE product_id = 717;
UPDATE products SET product_name = 'Wireless Audio Transmitter' WHERE product_id = 718;
UPDATE products SET product_name = 'Advanced Networking Book' WHERE product_id = 719;
UPDATE products SET product_name = 'Portable Media Hub Pro' WHERE product_id = 720;
UPDATE products SET product_name = 'Storage Utility Drawer Slim' WHERE product_id = 721;
UPDATE products SET product_name = 'Bluetooth Office Receiver' WHERE product_id = 722;
UPDATE products SET product_name = 'Desktop File Rack' WHERE product_id = 723;
UPDATE products SET product_name = 'Pocket Story Book' WHERE product_id = 724;
UPDATE products SET product_name = 'Classical Drama Collection' WHERE product_id = 725;
UPDATE products SET product_name = 'Photo Gift Card Combo' WHERE product_id = 726;
UPDATE products SET product_name = 'Luxury Mug and Teddy Set' WHERE product_id = 727;
UPDATE products SET product_name = 'Pocket Academic Reader' WHERE product_id = 728;
UPDATE products SET product_name = 'USB Smart Pointer' WHERE product_id = 729;
UPDATE products SET product_name = 'Modern Essay Reader' WHERE product_id = 730;
UPDATE products SET product_name = 'Storage Bin Utility Small' WHERE product_id = 731;
UPDATE products SET product_name = 'Campus Assignment Book' WHERE product_id = 732;
UPDATE products SET product_name = 'Executive Paper Tray Deluxe' WHERE product_id = 733;
UPDATE products SET product_name = 'Advanced Calculus Book' WHERE product_id = 734;
UPDATE products SET product_name = 'Portable Clip Light' WHERE product_id = 735;
UPDATE products SET product_name = 'Storage Wallet Pro' WHERE product_id = 736;
UPDATE products SET product_name = 'Bluetooth Media Dongle' WHERE product_id = 737;
UPDATE products SET product_name = 'Wireless Smart Pointer' WHERE product_id = 738;
UPDATE products SET product_name = 'Portable Mini Projector' WHERE product_id = 739;
UPDATE products SET product_name = 'Executive Storage Journal' WHERE product_id = 740;
UPDATE products SET product_name = 'Student Note Card Set' WHERE product_id = 741;
UPDATE products SET product_name = 'Love Mug Gift Box' WHERE product_id = 742;
UPDATE products SET product_name = 'Wireless Desk Presenter' WHERE product_id = 743;
UPDATE products SET product_name = 'Advanced Data Analytics' WHERE product_id = 744;
UPDATE products SET product_name = 'Storage Office Utility Rack' WHERE product_id = 745;
UPDATE products SET product_name = 'Photo Card Hamper' WHERE product_id = 746;
UPDATE products SET product_name = 'Premium Desk Folder Pro' WHERE product_id = 747;
UPDATE products SET product_name = 'Portable Media Receiver' WHERE product_id = 748;
UPDATE products SET product_name = 'Love Scrapbook Premium' WHERE product_id = 749;
UPDATE products SET product_name = 'USB Desktop Adapter' WHERE product_id = 750;
UPDATE products SET product_name = 'Storage Shelf Organizer Pro' WHERE product_id = 751;
UPDATE products SET product_name = 'Executive Marker Journal' WHERE product_id = 752;
UPDATE products SET product_name = 'Portable Basket Organizer' WHERE product_id = 753;
UPDATE products SET product_name = 'Rose and Chocolate Gift' WHERE product_id = 754;
UPDATE products SET product_name = 'Practical English Grammar' WHERE product_id = 755;
UPDATE products SET product_name = 'Introduction to Economics' WHERE product_id = 756;
UPDATE products SET product_name = 'Desk Utility Folder' WHERE product_id = 757;
UPDATE products SET product_name = 'Student Note Pocket Set' WHERE product_id = 758;
UPDATE products SET product_name = 'Wireless Streaming Hub' WHERE product_id = 759;
UPDATE products SET product_name = 'Custom Surprise Mug' WHERE product_id = 760;
UPDATE products SET product_name = 'Portable Smart Receiver' WHERE product_id = 761;
UPDATE products SET product_name = 'Bluetooth Utility Speaker' WHERE product_id = 762;
UPDATE products SET product_name = 'Introduction to Culture Studies' WHERE product_id = 763;
UPDATE products SET product_name = 'Executive Sticky Note Box' WHERE product_id = 764;
UPDATE products SET product_name = 'USB Type C Hub Pro' WHERE product_id = 765;
UPDATE products SET product_name = 'Fundamentals of Logic' WHERE product_id = 766;
UPDATE products SET product_name = 'Premium Student Marker Set' WHERE product_id = 767;
UPDATE products SET product_name = 'Software Testing Handbook' WHERE product_id = 768;
UPDATE products SET product_name = 'Modern Prose Collection' WHERE product_id = 769;
UPDATE products SET product_name = 'Crystal Memory Gift Box' WHERE product_id = 770;
UPDATE products SET product_name = 'Executive Desk Note Set' WHERE product_id = 771;
UPDATE products SET product_name = 'Premium Office Writing Set' WHERE product_id = 772;
UPDATE products SET product_name = 'Campus Writing Organizer' WHERE product_id = 773;
UPDATE products SET product_name = 'Pocket Literature Guide' WHERE product_id = 774;
UPDATE products SET product_name = 'Pocket Poetry Reader' WHERE product_id = 775;
UPDATE products SET product_name = 'Student Register Planner' WHERE product_id = 776;
UPDATE products SET product_name = 'Storage Box Portable' WHERE product_id = 777;
UPDATE products SET product_name = 'Luxury Surprise Card Box' WHERE product_id = 778;
UPDATE products SET product_name = 'Document Basket Large' WHERE product_id = 779;
UPDATE products SET product_name = 'Mini Utility Tray' WHERE product_id = 780;
UPDATE products SET product_name = 'Professional Writing Kit' WHERE product_id = 781;
UPDATE products SET product_name = 'Storage Wallet Case' WHERE product_id = 782;
UPDATE products SET product_name = 'Desk Shelf Storage Mini' WHERE product_id = 783;
UPDATE products SET product_name = 'Premium Journal Register' WHERE product_id = 784;
UPDATE products SET product_name = 'Campus Gel Pen Pack' WHERE product_id = 785;
UPDATE products SET product_name = 'Storage Drawer Office Set' WHERE product_id = 786;
UPDATE products SET product_name = 'Advanced Academic Reader' WHERE product_id = 787;
UPDATE products SET product_name = 'Executive Marker Pouch' WHERE product_id = 788;
UPDATE products SET product_name = 'Student Practical Notebook' WHERE product_id = 789;
UPDATE products SET product_name = 'Storage File Basket' WHERE product_id = 790;
UPDATE products SET product_name = 'Wireless Rechargeable Keyboard' WHERE product_id = 791;
UPDATE products SET product_name = 'Portable WiFi Extender' WHERE product_id = 792;
UPDATE products SET product_name = 'English Drama Notes' WHERE product_id = 793;
UPDATE products SET product_name = 'Love Ribbon Gift Set' WHERE product_id = 794;
UPDATE products SET product_name = 'Executive Highlighter Box' WHERE product_id = 795;
UPDATE products SET product_name = 'Chocolate Greeting Basket' WHERE product_id = 796;
UPDATE products SET product_name = 'Philosophy Essentials Book' WHERE product_id = 797;
UPDATE products SET product_name = 'Political Science Reader' WHERE product_id = 798;
UPDATE products SET product_name = 'Photo Note Gift Box' WHERE product_id = 799;
UPDATE products SET product_name = 'Literary Theory Handbook' WHERE product_id = 800;


UPDATE products SET product_name = 'Wireless Office Receiver' WHERE product_id = 801;
UPDATE products SET product_name = 'Mini Chocolate Note Box' WHERE product_id = 802;
UPDATE products SET product_name = 'Storage Utility Pouch' WHERE product_id = 803;
UPDATE products SET product_name = 'Professional Writing Companion' WHERE product_id = 804;
UPDATE products SET product_name = 'Decorative Storage Crate' WHERE product_id = 805;
UPDATE products SET product_name = 'Pocket Academic Dictionary' WHERE product_id = 806;
UPDATE products SET product_name = 'Storage Desk Drawer Pro' WHERE product_id = 807;
UPDATE products SET product_name = 'Fundamentals of Literature' WHERE product_id = 808;
UPDATE products SET product_name = 'Executive File Folder Set' WHERE product_id = 809;
UPDATE products SET product_name = 'USB Multimedia Adapter' WHERE product_id = 810;
UPDATE products SET product_name = 'Portable Desk Speaker' WHERE product_id = 811;
UPDATE products SET product_name = 'Mini Desktop Storage Box' WHERE product_id = 812;
UPDATE products SET product_name = 'Wireless Numeric Pad' WHERE product_id = 813;
UPDATE products SET product_name = 'USB Smart Hub' WHERE product_id = 814;
UPDATE products SET product_name = 'Academic Notes Register' WHERE product_id = 815;
UPDATE products SET product_name = 'Luxury Surprise Candle' WHERE product_id = 816;
UPDATE products SET product_name = 'Fundamentals of Sociology' WHERE product_id = 817;
UPDATE products SET product_name = 'Portable Smart Pointer Pro' WHERE product_id = 818;
UPDATE products SET product_name = 'Premium Desk Supply Box' WHERE product_id = 819;
UPDATE products SET product_name = 'Storage Basket Deluxe' WHERE product_id = 820;
UPDATE products SET product_name = 'Gift Hamper Signature Edition' WHERE product_id = 821;
UPDATE products SET product_name = 'Wireless Home Display Adapter' WHERE product_id = 822;
UPDATE products SET product_name = 'Modern Academic Reader' WHERE product_id = 823;
UPDATE products SET product_name = 'Portable Conference Microphone' WHERE product_id = 824;
UPDATE products SET product_name = 'USB Smart Charging Dock' WHERE product_id = 825;
UPDATE products SET product_name = 'Memory Basket Premium' WHERE product_id = 826;
UPDATE products SET product_name = 'Pocket Novel Edition' WHERE product_id = 827;
UPDATE products SET product_name = 'Mini Wireless Adapter' WHERE product_id = 828;
UPDATE products SET product_name = 'Executive Desk Basket' WHERE product_id = 829;
UPDATE products SET product_name = 'Office Utility Journal' WHERE product_id = 830;
UPDATE products SET product_name = 'Storage Caddy Compact' WHERE product_id = 831;
UPDATE products SET product_name = 'Business Strategy Handbook' WHERE product_id = 832;
UPDATE products SET product_name = 'Pocket Literature Collection' WHERE product_id = 833;
UPDATE products SET product_name = 'Custom Greeting Hamper' WHERE product_id = 834;
UPDATE products SET product_name = 'Portable Smart Remote' WHERE product_id = 835;
UPDATE products SET product_name = 'Storage Organizer Premium' WHERE product_id = 836;
UPDATE products SET product_name = 'Wireless Audio Station' WHERE product_id = 837;
UPDATE products SET product_name = 'Student Revision Notebook' WHERE product_id = 838;
UPDATE products SET product_name = 'Decorative Utility Box' WHERE product_id = 839;
UPDATE products SET product_name = 'Campus Stationery Journal' WHERE product_id = 840;
UPDATE products SET product_name = 'USB Study Light' WHERE product_id = 841;
UPDATE products SET product_name = 'Elegant Teddy Gift Basket' WHERE product_id = 842;
UPDATE products SET product_name = 'Storage Tray Stackable' WHERE product_id = 843;
UPDATE products SET product_name = 'Executive Office Basket' WHERE product_id = 844;
UPDATE products SET product_name = 'Mini Romantic Card Box' WHERE product_id = 845;
UPDATE products SET product_name = 'Premium Office Marker Set' WHERE product_id = 846;
UPDATE products SET product_name = 'Professional Desk Folder' WHERE product_id = 847;
UPDATE products SET product_name = 'Gift Sticker Decorative Set' WHERE product_id = 848;
UPDATE products SET product_name = 'Portable Multimedia Device' WHERE product_id = 849;
UPDATE products SET product_name = 'Luxury Memory Hamper' WHERE product_id = 850;
UPDATE products SET product_name = 'Campus Writing Notebook' WHERE product_id = 851;
UPDATE products SET product_name = 'USB Portable Speaker' WHERE product_id = 852;
UPDATE products SET product_name = 'Premium Student Stationery Kit' WHERE product_id = 853;
UPDATE products SET product_name = 'Wireless Office Hub' WHERE product_id = 854;
UPDATE products SET product_name = 'Romantic Celebration Basket' WHERE product_id = 855;
UPDATE products SET product_name = 'Executive Sticky Memo Box' WHERE product_id = 856;
UPDATE products SET product_name = 'Contemporary Poetry Reader' WHERE product_id = 857;
UPDATE products SET product_name = 'Custom Memory Jar Gift' WHERE product_id = 858;
UPDATE products SET product_name = 'Storage Office Pouch' WHERE product_id = 859;
UPDATE products SET product_name = 'Portable Smart Charger' WHERE product_id = 860;
UPDATE products SET product_name = 'Mini Luxury Gift Set' WHERE product_id = 861;
UPDATE products SET product_name = 'Handmade Surprise Basket' WHERE product_id = 862;
UPDATE products SET product_name = 'Pocket Essay Collection' WHERE product_id = 863;
UPDATE products SET product_name = 'Decorative Love Photo Box' WHERE product_id = 864;
UPDATE products SET product_name = 'Wireless Desktop Controller' WHERE product_id = 865;
UPDATE products SET product_name = 'Storage Utility Wallet' WHERE product_id = 866;
UPDATE products SET product_name = 'Executive Desk Toolkit' WHERE product_id = 867;
UPDATE products SET product_name = 'USB LED Reading Lamp' WHERE product_id = 868;
UPDATE products SET product_name = 'Storage Box Signature Edition' WHERE product_id = 869;
UPDATE products SET product_name = 'Portable Bluetooth Controller' WHERE product_id = 870;
UPDATE products SET product_name = 'Fundamentals of History' WHERE product_id = 871;
UPDATE products SET product_name = 'Luxury Chocolate Candle Box' WHERE product_id = 872;
UPDATE products SET product_name = 'Business Management Workbook' WHERE product_id = 873;
UPDATE products SET product_name = 'Professional Desk Label Kit' WHERE product_id = 874;
UPDATE products SET product_name = 'Executive Storage Notebook' WHERE product_id = 875;
UPDATE products SET product_name = 'Pocket World Literature' WHERE product_id = 876;
UPDATE products SET product_name = 'Wireless Desk Presenter Pro' WHERE product_id = 877;
UPDATE products SET product_name = 'Portable Type C Adapter' WHERE product_id = 878;
UPDATE products SET product_name = 'Luxury Customized Gift Bag' WHERE product_id = 879;
UPDATE products SET product_name = 'Advanced Literary Studies' WHERE product_id = 880;
UPDATE products SET product_name = 'Desktop Storage Journal' WHERE product_id = 881;
UPDATE products SET product_name = 'Executive Stationery Combo' WHERE product_id = 882;
UPDATE products SET product_name = 'Romantic Handmade Card Set' WHERE product_id = 883;
UPDATE products SET product_name = 'Portable Wireless Display' WHERE product_id = 884;
UPDATE products SET product_name = 'Festival Love Basket' WHERE product_id = 885;
UPDATE products SET product_name = 'USB Smart Audio Dongle' WHERE product_id = 886;
UPDATE products SET product_name = 'Wireless Desk Microphone' WHERE product_id = 887;
UPDATE products SET product_name = 'Professional Writing Marker Kit' WHERE product_id = 888;
UPDATE products SET product_name = 'Executive Utility Organizer' WHERE product_id = 889;
UPDATE products SET product_name = 'Software Engineering Workbook' WHERE product_id = 890;
UPDATE products SET product_name = 'USB Streaming Adapter' WHERE product_id = 891;
UPDATE products SET product_name = 'Student Desk Diary' WHERE product_id = 892;
UPDATE products SET product_name = 'Introduction to Media Studies' WHERE product_id = 893;
UPDATE products SET product_name = 'Pocket Academic Grammar' WHERE product_id = 894;
UPDATE products SET product_name = 'Chocolate Surprise Gift Pack' WHERE product_id = 895;
UPDATE products SET product_name = 'Premium Office Notebook Set' WHERE product_id = 896;
UPDATE products SET product_name = 'Portable Study Adapter' WHERE product_id = 897;
UPDATE products SET product_name = 'Advanced Reference Companion' WHERE product_id = 898;
UPDATE products SET product_name = 'Pocket Business Reader' WHERE product_id = 899;
UPDATE products SET product_name = 'Storage File Wallet' WHERE product_id = 900;
UPDATE products SET product_name = 'Wireless Smart Office Mouse' WHERE product_id = 901;
UPDATE products SET product_name = 'Executive Desk Storage Set' WHERE product_id = 902;
UPDATE products SET product_name = 'Gift Mug and Candle Basket' WHERE product_id = 903;
UPDATE products SET product_name = 'Portable Office Display Adapter' WHERE product_id = 904;
UPDATE products SET product_name = 'Advanced Study Reference Book' WHERE product_id = 905;
UPDATE products SET product_name = 'Campus Daily Planner' WHERE product_id = 906;
UPDATE products SET product_name = 'Pocket Literary Companion' WHERE product_id = 907;
UPDATE products SET product_name = 'Luxury Memory Gift Hamper' WHERE product_id = 908;
UPDATE products SET product_name = 'Romantic Rose Card Box' WHERE product_id = 909;
UPDATE products SET product_name = 'Pocket Contemporary Reader' WHERE product_id = 910;
UPDATE products SET product_name = 'Premium Office Supply Basket' WHERE product_id = 911;
UPDATE products SET product_name = 'Desktop Utility Notebook' WHERE product_id = 912;
UPDATE products SET product_name = 'Advanced Technical Writing' WHERE product_id = 913;
UPDATE products SET product_name = 'Wireless Smart Desk Device' WHERE product_id = 914;
UPDATE products SET product_name = 'Storage Pouch Premium' WHERE product_id = 915;
UPDATE products SET product_name = 'Portable Smart Office Bell' WHERE product_id = 916;
UPDATE products SET product_name = 'Wireless Presentation Remote' WHERE product_id = 917;
UPDATE products SET product_name = 'Academic Research Companion' WHERE product_id = 918;
UPDATE products SET product_name = 'Luxury Rose and Chocolate Hamper' WHERE product_id = 919;
UPDATE products SET product_name = 'Executive Storage Register' WHERE product_id = 920;
UPDATE products SET product_name = 'Desk Utility Planner Pro' WHERE product_id = 921;
UPDATE products SET product_name = 'Mini Anniversary Card Set' WHERE product_id = 922;
UPDATE products SET product_name = 'Premium Study Stationery Pack' WHERE product_id = 923;
UPDATE products SET product_name = 'Professional Desk Note Set' WHERE product_id = 924;
UPDATE products SET product_name = 'Festival Memory Card Box' WHERE product_id = 925;
UPDATE products SET product_name = 'Pocket Research Reader' WHERE product_id = 926;
UPDATE products SET product_name = 'Advanced Literature Handbook' WHERE product_id = 927;
UPDATE products SET product_name = 'Customized Mug Basket Deluxe' WHERE product_id = 928;
UPDATE products SET product_name = 'Mini Celebration Card Box' WHERE product_id = 929;
UPDATE products SET product_name = 'Wireless Audio Controller' WHERE product_id = 930;
UPDATE products SET product_name = 'Portable Wireless Hub Pro' WHERE product_id = 931;
UPDATE products SET product_name = 'Storage Notebook Organizer' WHERE product_id = 932;
UPDATE products SET product_name = 'Decorative Surprise Gift Tray' WHERE product_id = 933;
UPDATE products SET product_name = 'Executive Stationery Storage Box' WHERE product_id = 934;
UPDATE products SET product_name = 'Rose and Candle Surprise Set' WHERE product_id = 935;
UPDATE products SET product_name = 'Professional Desk Marker Set' WHERE product_id = 936;
UPDATE products SET product_name = 'Premium Office Writing Folder' WHERE product_id = 937;
UPDATE products SET product_name = 'Advanced Language Studies' WHERE product_id = 938;
UPDATE products SET product_name = 'Pocket Academic Story Book' WHERE product_id = 939;
UPDATE products SET product_name = 'Handmade Memory Photo Box' WHERE product_id = 940;
UPDATE products SET product_name = 'Student Utility Register' WHERE product_id = 941;
UPDATE products SET product_name = 'Mini Surprise Rose Hamper' WHERE product_id = 942;
UPDATE products SET product_name = 'USB Portable Office Lamp' WHERE product_id = 943;
UPDATE products SET product_name = 'Advanced Literary Criticism' WHERE product_id = 944;
UPDATE products SET product_name = 'Wireless Smart Desk Hub' WHERE product_id = 945;
UPDATE products SET product_name = 'Storage Office Notebook Box' WHERE product_id = 946;
UPDATE products SET product_name = 'Mini Pocket Reader' WHERE product_id = 947;
UPDATE products SET product_name = 'Professional Utility Basket' WHERE product_id = 948;
UPDATE products SET product_name = 'Executive Desk Writing Kit' WHERE product_id = 949;
UPDATE products SET product_name = 'Premium Student Planner' WHERE product_id = 950;
UPDATE products SET product_name = 'Pocket Academic Notebook' WHERE product_id = 951;
UPDATE products SET product_name = 'Wireless Office Display Hub' WHERE product_id = 952;
UPDATE products SET product_name = 'Professional Note Organizer' WHERE product_id = 953;
UPDATE products SET product_name = 'Storage Utility Journal Pro' WHERE product_id = 954;
UPDATE products SET product_name = 'Executive Study Supply Set' WHERE product_id = 955;
UPDATE products SET product_name = 'Portable Wireless Charging Hub' WHERE product_id = 956;
UPDATE products SET product_name = 'Luxury Mug Surprise Basket' WHERE product_id = 957;
UPDATE products SET product_name = 'Storage Box Office Deluxe' WHERE product_id = 958;
UPDATE products SET product_name = 'Romantic Memory Gift Set' WHERE product_id = 959;
UPDATE products SET product_name = 'Mini Desk Accessory Box' WHERE product_id = 960;
UPDATE products SET product_name = 'Customized Candle Memory Hamper' WHERE product_id = 961;
UPDATE products SET product_name = 'Executive Desktop Planner' WHERE product_id = 962;
UPDATE products SET product_name = 'Storage Rack Notebook Set' WHERE product_id = 963;
UPDATE products SET product_name = 'Advanced Cultural Studies' WHERE product_id = 964;
UPDATE products SET product_name = 'Portable Office Media Device' WHERE product_id = 965;
UPDATE products SET product_name = 'Desk Utility Storage Pro' WHERE product_id = 966;
UPDATE products SET product_name = 'Pocket Academic Classics' WHERE product_id = 967;
UPDATE products SET product_name = 'Luxury Surprise Rose Box' WHERE product_id = 968;
UPDATE products SET product_name = 'Wireless Multimedia Controller' WHERE product_id = 969;
UPDATE products SET product_name = 'Professional Literature Companion' WHERE product_id = 970;
UPDATE products SET product_name = 'Pocket Study Dictionary' WHERE product_id = 971;
UPDATE products SET product_name = 'Storage Folder Executive Edition' WHERE product_id = 972;
UPDATE products SET product_name = 'Advanced Writing Practice Book' WHERE product_id = 973;
UPDATE products SET product_name = 'USB Portable Desk Tool' WHERE product_id = 974;
UPDATE products SET product_name = 'Wireless Office Presentation Hub' WHERE product_id = 975;
UPDATE products SET product_name = 'Academic Note Keeper' WHERE product_id = 976;
UPDATE products SET product_name = 'Premium Desk Marker Box' WHERE product_id = 977;
UPDATE products SET product_name = 'Gift Card and Mug Combo' WHERE product_id = 978;
UPDATE products SET product_name = 'Executive Office Utility Set' WHERE product_id = 979;
UPDATE products SET product_name = 'Pocket Educational Reader' WHERE product_id = 980;
UPDATE products SET product_name = 'Professional Desk Supply Folder' WHERE product_id = 981;
UPDATE products SET product_name = 'Luxury Customized Surprise Set' WHERE product_id = 982;
UPDATE products SET product_name = 'Premium Stationery Journal' WHERE product_id = 983;
UPDATE products SET product_name = 'Romantic Gift Hamper Deluxe' WHERE product_id = 984;
UPDATE products SET product_name = 'Portable Wireless Desk Device' WHERE product_id = 985;
UPDATE products SET product_name = 'Storage Basket Office Pro' WHERE product_id = 986;
UPDATE products SET product_name = 'Executive Study Register' WHERE product_id = 987;
UPDATE products SET product_name = 'Professional Office Notebook' WHERE product_id = 988;
UPDATE products SET product_name = 'Campus Pocket Planner' WHERE product_id = 989;
UPDATE products SET product_name = 'Storage Utility File Pro' WHERE product_id = 990;
UPDATE products SET product_name = 'Pocket Academic Workbook' WHERE product_id = 991;
UPDATE products SET product_name = 'Luxury Memory Surprise Hamper' WHERE product_id = 992;
UPDATE products SET product_name = 'Advanced Academic Writing' WHERE product_id = 993;
UPDATE products SET product_name = 'Wireless Smart Utility Hub' WHERE product_id = 994;
UPDATE products SET product_name = 'Custom Mug Gift Hamper' WHERE product_id = 995;
UPDATE products SET product_name = 'Student Planner Companion' WHERE product_id = 996;
UPDATE products SET product_name = 'Pocket Learning Journal' WHERE product_id = 997;
UPDATE products SET product_name = 'Storage Executive Basket' WHERE product_id = 998;
UPDATE products SET product_name = 'Office Utility Marker Kit' WHERE product_id = 999;
UPDATE products SET product_name = 'Portable Wireless Study Hub' WHERE product_id = 1000;



UPDATE products SET image_url = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Spiral-bound_notebooks.JPG' WHERE product_id = 1;
UPDATE products SET image_url = 'https://images.unsplash.com/photo-1644463589256-02679b9c0767?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVzayUyMG9yZ2FuaXplcnxlbnwwfHwwfHx8MA%3D%3D&ixlib=rb-4.1.0&q=60&w=3000' WHERE product_id = 2;
UPDATE products SET image_url = 'https://images.unsplash.com/photo-1711112109420-ecf9be11abb7?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGJpcnRoZGF5JTIwY2FyZHN8ZW58MHx8MHx8fDA%3D&ixlib=rb-4.1.0&q=60&w=3000' WHERE product_id = 3;
UPDATE products SET image_url = 'https://covers.openlibrary.org/b/olid/OL34192801M-L.jpg' WHERE product_id = 4;
UPDATE products SET image_url = 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&ixlib=rb-4.1.0&q=60&w=3000' WHERE product_id = 5;
UPDATE products SET image_url = 'https://images.unsplash.com/photo-1551373884-8a0750074df7?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBpY3R1cmUlMjBmcmFtZXN8ZW58MHx8MHx8fDA%3D&ixlib=rb-4.1.0&q=60&w=3000' WHERE product_id = 6;
UPDATE products SET image_url = 'https://images.unsplash.com/photo-1760348213270-7cd00b8c3405?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&ixlib=rb-4.1.0&q=60&w=3000' WHERE product_id = 7;
UPDATE products SET image_url = 'https://covers.openlibrary.org/b/olid/OL33735990M-L.jpg' WHERE product_id = 8;
UPDATE products SET image_url = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Whiteboard%20with%20markers.jpg' WHERE product_id = 9;
UPDATE products SET image_url = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sticky_notes.svg' WHERE product_id = 10;

